Homework for Lecture 8
impiia/react-2024-01-15 pull request #9
Opened 2024-02-14 17:33 UTC by impiia

1. Refactor data fetching to RTK Query
2. Implemented adding a new review (using the review form). A loader is displaying on the form, it is clearing after successful saving, and a request for restaurant reviews is executing.

2024-02-15 15:56 UTC, SArchieEdu requested changes

2024-02-15 15:56 UTC, SArchieEdu commented on src/components/review-form/component.jsx
> +export const ReviewForm = ({ user, review, restaurantId, onEditCancel }) => {
Покажу на лекции как сделать иначе, сейчас компонент перегружен. После разбора лучше переделайте.

2024-02-15 15:56 UTC, SArchieEdu commented on src/components/dish/container.jsx
> +    const { isLoading, data: dish } = useGetDishByIdQuery(dishId);
очень много запросов будет, лучше грузить по ресторану

2024-02-17 06:29 UTC, impiia commented on src/components/dish/container.jsx
> +    const { isLoading, data: dish } = useGetDishByIdQuery(dishId);
переделала, но тогда у меня ломается корзина (в ней от блюда остается только id, а названия нет), не логично же делать выборку по ресторану в компоненте DishContainer и пробрасывать до туда restaurantId? Выборка по ресторану просится в MenuContainer, а в корзине menu нет, туда сразу блюда складываются, и получается, что в корзине остаются одни id блюд

2024-02-19 15:07 UTC, SArchieEdu commented on src/components/dish/container.jsx
> +    const { isLoading, data: dish } = useGetDishByIdQuery(dishId);
можно будет доделать корзину в дз по роутингу, там будет адишка ресторана в урле. Можно будет взять ее от туда и отобразить корзину текущего ресторана. А при смене ресторана сбрасывать

2024-02-19 15:07 UTC, SArchieEdu approved these changes

2024-02-19 15:09 UTC, SArchieEdu commented on src/components/dish/container.jsx
> +    const { isLoading, data: dish } = useGetDishByIdQuery(dishId);
либо разделить корзину по ресторанам. cart: {restaurantId: {id: amount}} примерно такую структуру использовать

2024-02-19 15:56 UTC, merged